
#####################################################
## model_provider 模型运行参数
# API密钥用于身份验证和授权
api_key: ""
# 本地运行时使用的模型名称
local_model_name: "qwen-max-longcontext"
# 远程服务器上使用的模型名称
remote_model_name: "Qwen/Qwen2-7B-Instruct"
# 模型缓存的存储目录
cache_dir: "/root/autodl-tmp/hug/"
# 运行模型的设备，例如 'cuda' 或 'cpu'
device: "cuda"
# 最大重试次数设置
max_retry_time: 1
# 标志是否在本地运行模型
nolocal_run: true

